version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: "disabled"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 2
    rebase-strategy: "disabled"
    groups:
      junit-jupiter:
        patterns:
          - "org.junit.jupiter:*"
          - "org.junit.platform:*"
    ignore:
      - dependency-name: "com.github.jmongard.git-semver-plugin"
