name: "Continuous Integration"

on: [push]

jobs:
  build:
    name: "Build and Tests"
    runs-on: ubuntu-24.04

    steps:

    - name: "Checkout"
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: "Set up JDK"
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '21'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: wrapper
        # disable reading from cache on re-runs to fix possible caching issues
        cache-write-only: ${{ fromJSON(github.run_attempt) != 1 }}

    - name: "Build"
      run: ./gradlew assemble --scan --console=plain --build-cache

    - name: "Test"
      run: ./gradlew check --scan --console=plain --build-cache

    - name: "Publish Test Report"
      uses: mikepenz/action-junit-report@v5
      if: ${{ failure() }}
      with:
        report_paths: "**/build/test-results/**/TEST-*.xml"
        require_tests: false
