name: "Continuous Integration"

on: [push]

jobs:
  build:
    name: "CI"
    runs-on: ubuntu-24.04

    steps:

    - name: "Checkout"
      uses: actions/checkout@v4

    - name: "Set up JDK"
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '21'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: wrapper
        # disable reading from cache on re-runs to fix possible caching issues
        cache-write-only: ${{ fromJSON(github.run_attempt) != 1 }}

    - name: "Build"
      run: ./gradlew assemble --scan --console=plain --build-cache

    - name: "Test"
      run: ./gradlew check --scan --console=plain --build-cache

    - name: "Publish Test Report"
      uses: mikepenz/action-junit-report@v5
      if: ${{ failure() }}
      with:
        report_paths: "**/build/test-results/**/TEST-*.xml"
        require_tests: false

    - name: "Publish (Pre-) Release"
      if: ${{ github.ref == 'refs/heads/main' }}
      env:
        JRELEASER_CONFIG_CONTENT: ${{ secrets.JRELEASER_CONFIG_CONTENT }}
      run: |
        echo "$JRELEASER_CONFIG_CONTENT" > ~/.jreleaser/config.toml
        ./gradlew publish jreleaserFullRelease --scan --console=plain --build-cache
